# Ski Resort Analysis

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import pymysql

In [14]:
rds_connection_string = "root:<password>@localhost:3306/ski_resorts_db"
engine = create_engine(f'mysql://{rds_connection_string}')

In [15]:
# check for tables
engine.table_names()

['skiresort']

In [17]:
# setting variable to reference the csv file
skiResorts = "skiResort.csv"
# bringing the csv into a pandas dataframe
resorts_df = pd.read_csv(skiResorts)
# convert null / NaN values to zero
resorts_df.fillna(0, inplace=True)
# printing first five records in the dataframe
resorts_df.head()

,ResortName,Continent,Country,StateProvince,URL,Altitude,Easy,Intermed,Difficult,ropewayGondolaLift,...,Advanced,SnowParks,CCTrails,AerialTramway,RopeToeBeginnerLift,PeopleMover,CombinedInstallation,CogRailway,HelicopterHeli-skiing,SnowCaterpillars
0,3-5-pigadia-naoussa,Europe,Greece,Central Macedonia,http://www.skiresort.info/ski-resort/3-5-pigad...,2005,4.0,3.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4-vallees-verbierla-tzoumaznendazveysonnazthyon,Europe,Switzerland,Lemanic Region,http://www.skiresort.info/ski-resort/4-vallees...,3330,107.0,202.0,103.0,0.0,...,5.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,49-degrees-north-mountain-resort,North America,USA,Washington State,http://www.skiresort.info/ski-resort/49-degree...,1760,20.0,27.0,21.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,aadneram-skitrekk,Europe,Norway,Vest-Agder,http://www.skiresort.info/ski-resort/aadneram-...,680,3.5,0.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,aal-skisenter,Europe,Norway,Buskerud,http://www.skiresort.info/ski-resort/aal-skise...,1040,5.0,2.0,2.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0