# Ski Resort Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
import pymysql

In [4]:
rds_connection_string = "root:<password>@localhost:3306/ski_resorts_db"
engine = create_engine(f'mysql://{rds_connection_string}')

In [5]:
# check for tables
engine.table_names()

['clean_skiresortnortamerica', 'skiresort']

In [8]:
# setting variable to reference the csv file
skiResorts = "Resources/clean_skiResortNortAmerica.csv"
# bringing the csv into a pandas dataframe
resorts_df = pd.read_csv(skiResorts)
# convert null / NaN values
resorts_df.fillna("empty", inplace=True)
# printing first five records in the dataframe
resorts_df.head()

,ID,ResortName,Continent,Country,StateProvince,URL,Altitude,Easy,Intermediate,Difficult,...,Cross-countryTrails,AerialTramwayReverseRopeway,RopeTowBeginnerLift,PeopleMover,CombinedGondolaChair,CogRailway,Helicopter,SnowCaterpillars,Latitude,Longitude
0,2,49-degrees-north-mountain-resort,North America,USA,Washington State,http://www.skiresort.info/ski-resort/49-degree...,1760,20,27,21,...,empty,empty,0,empty,empty,empty,empty,empty,48.301097,-117.562916
1,14,abenaki,North America,USA,New Hampshire,http://www.skiresort.info/ski-resort/abenaki/,250,0.5,0.3,0.2,...,empty,empty,empty,empty,empty,empty,empty,empty,43.611548,-71.229107
2,15,aberdeen-heli-prince-george,North America,Canada,British Columbia,http://www.skiresort.info/ski-resort/aberdeen-...,0,empty,empty,empty,...,empty,empty,empty,empty,empty,empty,0,empty,53.882664,-122.676198
3,24,adamants,North America,Canada,British Columbia,http://www.skiresort.info/ski-resort/adamants/,3100,empty,empty,empty,...,empty,empty,empty,empty,empty,empty,0,empty,51.632117,-118.169138
4,25,adanac-ski-hill,North America,Canada,Ontario,http://www.skiresort.info/ski-resort/adanac-sk...,340,1.3,0.6,0.1,...,empty,empty,empty,0,empty,empty,empty,empty,46.510561,-80.960432